# Generated by Django 3.0.3 on 2020-02-26 09:27

from django.db import migrations, models
import sensorreg.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceID', models.IntegerField()),
                ('IP', models.GenericIPAddressField(protocol='IPv4')),
                ('Port', models.IntegerField()),
                ('MacAddress', models.CharField(max_length=20, validators=[sensorreg.validator.validate_MAC])),
                ('AdministrativeRegion', models.CharField(choices=[('gangwon-do', 'Gangwon-do'), ('gyeonggi-do', 'Gyeongii-do')], max_length=100)),
                ('InstallationRoute', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=100)),
                ('InstallationLocation', models.CharField(max_length=100)),
                ('GPSCoordinates', models.CharField(max_length=100, validators=[sensorreg.validator.validate_GPS])),
                ('InterlockDeviceInformation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('MacAddress', models.IntegerField()),
                ('ManagerName', models.CharField(max_length=100)),
                ('ManagerPhoneNo', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
                ('FinalApprover', models.CharField(max_length=100)),
            ],
        ),
    ]
