# Generated by Django 3.0.3 on 2020-02-27 04:40

from django.db import migrations, models
import sensorreg.validator


class Migration(migrations.Migration):

    dependencies = [
        ('sensorreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterlockDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.IntegerField(unique=True)),
                ('IP', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('Port', models.IntegerField(default=23000)),
                ('Device_Type', models.CharField(choices=[('a', 'Device of Sprinkler'), ('b', 'CCTV'), ('c', 'Electronic Board'), ('d', 'Disaster Broadcast')], max_length=100)),
                ('Remarks', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='DeviceID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='GPSCoordinates',
            field=models.CharField(default='10.141932, 10.371094', max_length=100, validators=[sensorreg.validator.validate_GPS]),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='IP',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='InterlockDeviceInformation',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='MacAddress',
            field=models.CharField(default='aa:bb:cc:dd:ee:ff', max_length=20, validators=[sensorreg.validator.validate_MAC]),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='Port',
            field=models.IntegerField(default=23000),
        ),
    ]
